import PrelineScript from "@/Components/PrelineScript";
import "./globals.css";
import { Lato } from "next/font/google";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lato.className} data-theme="light">
        {children}</body>
      <PrelineScript />
    </html>
  );
}
